### ISSUE TITLE
yard 0.6.7 breaks yard-spellcheck.

### ISSUE THREAD

**Issue by postmodern** [postmodern/yard-spellcheck#2]
<pre>
/home/hal/.rvm/gems/ruby-1.9.2-p180/gems/yard-0.6.7/lib/yard/registry_store.rb:54:in `[]=': can't add a new key into hash during iteration (RuntimeError)
    from /home/hal/.rvm/gems/ruby-1.9.2-p180/gems/yard-0.6.7/lib/yard/registry_store.rb:54:in `put'
    from /home/hal/.rvm/gems/ruby-1.9.2-p180/gems/yard-0.6.7/lib/yard/registry_store.rb:38:in `get'
    from /home/hal/.rvm/gems/ruby-1.9.2-p180/gems/yard-0.6.7/lib/yard/registry.rb:234:in `at'
    from /home/hal/.rvm/gems/ruby-1.9.2-p180/gems/yard-0.6.7/lib/yard/serializers/yardoc_serializer.rb:20:in `method_missing'
    from /home/hal/.rvm/gems/ruby-1.9.2-p180/gems/yard-0.6.7/lib/yard/serializers/yardoc_serializer.rb:86:in `dump'
    from /home/hal/.rvm/gems/ruby-1.9.2-p180/gems/yard-0.6.7/lib/yard/serializers/yardoc_serializer.rb:86:in `dump'
    from /home/hal/.rvm/gems/ruby-1.9.2-p180/gems/yard-0.6.7/lib/yard/serializers/yardoc_serializer.rb:65:in `serialize'
    from /home/hal/.rvm/gems/ruby-1.9.2-p180/gems/yard-0.6.7/lib/yard/registry_store.rb:143:in `save'
    from /home/hal/.rvm/gems/ruby-1.9.2-p180/gems/yard-0.6.7/lib/yard/registry.rb:157:in `save'
    from /home/hal/.rvm/gems/ruby-1.9.2-p180/gems/yard-0.6.7/lib/yard/cli/yardoc.rb:209:in `run'
    from /home/hal/.rvm/gems/ruby-1.9.2-p180/gems/yard-0.6.7/lib/yard/cli/command.rb:13:in `run'
    from /home/hal/.rvm/gems/ruby-1.9.2-p180/gems/yard-spellcheck-0.1.1/lib/yard/cli/spellcheck.rb:42:in `run'
    from /home/hal/.rvm/gems/ruby-1.9.2-p180/gems/yard-0.6.7/lib/yard/cli/command.rb:13:in `run'
    from /home/hal/.rvm/gems/ruby-1.9.2-p180/gems/yard-spellcheck-0.1.1/bin/yard-spellcheck:6:in `<top (required)>'
    from /home/hal/.rvm/gems/ruby-1.9.2-p180/bin/yard-spellcheck:19:in `load'
    from /home/hal/.rvm/gems/ruby-1.9.2-p180/bin/yard-spellcheck:19:in `<main>'
</pre>

**Comment by postmodern** [comment]
Fixed long ago.
